In [1]:
import pandas as pd

In [2]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os

password = os.environ["DB_PASSWORD"]

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
                        f"mysql+pymysql://root:{password}@localhost:3306/foodhub"
                        )

print("Connection successful!")

Connection successful!

### Section 1 - Customer Spending

#### 1. Top 10 Customers by Total Spend

In [5]:
query = """select
                customer_id,
                count(*) as total_orders,
                round(sum(cost_of_the_order),2) as total_spend
           from product_events
           group by customer_id
           order by total_spend desc
           limit 10"""
pd.read_sql(query, engine)

   customer_id  total_orders  total_spend
0        52832            13       225.80
1       250494             8       183.83
2        47440            10       158.18
3       276192             7       146.46
4        83287             9       139.31
5       259341             7       130.81
6        97991             6       122.03
7        82041             7       120.92
8       115213             6       115.40
9        60039             4       109.76

#### 2. Average Spend Per Customer

In [6]:
query = """select
                customer_id,
                round(avg(cost_of_the_order), 2) as avg_order_value
           from product_events
           group by customer_id
           order by avg_order_value desc"""
pd.read_sql(query, engine)

      customer_id  avg_order_value
0          116992            33.32
1          123780            33.03
2          362068            33.03
3          212469            33.03
4          304587            33.03
...           ...              ...
1195        64754             5.34
1196       339144             5.05
1197       318665             4.90
1198        50123             4.85
1199       133617             4.75

[1200 rows x 2 columns]

#### 3. Customers With Highest Number of Orders

In [7]:
query = """select
                customer_id,
                count(*) as total_orders
           from product_events
           group by customer_id
           order by total_orders desc"""
pd.read_sql(query, engine)

      customer_id  total_orders
0           52832            13
1           47440            10
2           83287             9
3          250494             8
4           82041             7
...           ...           ...
1195       106324             1
1196       138586             1
1197        97838             1
1198       292602             1
1199       397537             1

[1200 rows x 2 columns]

#### 4. Customer Segmentation

In [8]:
query = """select
                customer_id,
                round(sum(cost_of_the_order), 2) as total_spend,
                case
                    when sum(cost_of_the_order) >= 100 then 'high value'
                    when sum(cost_of_the_order) >= 50 then 'medium value'
                else 'low value'
                end as customer_segment
           from product_events
           group by customer_id
           order by total_spend desc"""
pd.read_sql(query, engine)

      customer_id  total_spend customer_segment
0           52832       225.80       high value
1          250494       183.83       high value
2           47440       158.18       high value
3          276192       146.46       high value
4           83287       139.31       high value
...           ...          ...              ...
1195        64754         5.34        low value
1196       339144         5.05        low value
1197       318665         4.90        low value
1198        50123         4.85        low value
1199       133617         4.75        low value

[1200 rows x 3 columns]

#### 5. Average Restaurants Viewed

In [9]:
query = """select
                round(avg(restaurants_viewed), 2) as avg_restaurants_viewed
           from product_events"""
pd.read_sql(query, engine)

   avg_restaurants_viewed
0                    3.38

#### 6. Customers Viewing The Most Restaurants

In [10]:
query = """select
                customer_id,
                sum(restaurants_viewed) as total_views
           from product_events
           group by customer_id
           order by total_views desc
           limit 10"""
pd.read_sql(query, engine)

   customer_id  total_views
0        52832         52.0
1        83287         39.0
2        47440         34.0
3        60052         26.0
4       115213         26.0
5       250494         25.0
6       142461         24.0
7        78939         24.0
8        82041         23.0
9        81110         23.0

#### 7. Coupon Usage Percentage

In [11]:
query = """select
                round(avg(coupon_used) * 100, 2) as coupon_usage_percentage
           from product_events"""
pd.read_sql(query, engine)

   coupon_usage_percentage
0                    34.04

#### 8. Coupon Usage by City

In [12]:
query = """select
                city,
                round(avg(coupon_used) * 100, 2) as coupon_usage_percentage
           from product_events
           group by city
           order by coupon_usage_percentage desc"""

pd.read_sql(query, engine)

        city  coupon_usage_percentage
0     Mumbai                    35.59
1    Chennai                    35.20
2      Delhi                    34.52
3  Hyderabad                    33.78
4       Pune                    33.56
5  Bangalore                    32.75

#### 9. Average Order Value by Acquisition Channel

In [13]:
query = """
select
    acquisition_channel,
    round(avg(cost_of_the_order), 2) as avg_order_value
from product_events
group by acquisition_channel
order by avg_order_value desc
"""

pd.read_sql(query, engine)

  acquisition_channel  avg_order_value
0            Referral            16.86
1            Facebook            16.60
2             Organic            16.46
3          Google Ads            16.44
4           Instagram            16.25

#### 10. Customer Count by Acquisition Channel

In [14]:
query = """
select
    acquisition_channel,
    count(distinct customer_id) as total_customers
from product_events
group by acquisition_channel
order by total_customers desc
"""

pd.read_sql(query, engine)

  acquisition_channel  total_customers
0             Organic              556
1          Google Ads              193
2           Instagram              178
3            Referral              171
4            Facebook              102

#### 11. Revenue by Device Type

In [15]:
query = """
select
    device_type,
    round(sum(cost_of_the_order), 2) as total_revenue
from product_events
group by device_type
order by total_revenue desc
"""

pd.read_sql(query, engine)

  device_type  total_revenue
0     Android       23388.99
1         iOS        7925.83

#### 12. Average Rating by Device Type

In [16]:
query = """
select
    device_type,
    round(avg(rating), 2) as avg_rating
from product_events
group by device_type
order by avg_rating desc
"""

pd.read_sql(query, engine)

  device_type  avg_rating
0     Android        2.66
1         iOS        2.65

#### 13. Recommendation Click-Through Rate (CTR)

In [17]:
query = """
select
    round(avg(recommendation_clicked) * 100, 2) as recommendation_ctr
from product_events
"""

pd.read_sql(query, engine)

   recommendation_ctr
0               24.76

#### 14. Recommendation CTR by Device

In [18]:
query = """
select
    device_type,
    round(avg(recommendation_clicked) * 100, 2) as recommendation_ctr
from product_events
group by device_type
order by recommendation_ctr desc
"""

pd.read_sql(query, engine)

  device_type  recommendation_ctr
0     Android               25.66
1         iOS               22.22

#### 15. Cart Creation Rate by Acquisition Channel

In [19]:
query = """
select
    acquisition_channel,
    round(avg(cart_created) * 100, 2) as cart_creation_rate
from product_events
group by acquisition_channel
order by cart_creation_rate desc
"""

pd.read_sql(query, engine)

  acquisition_channel  cart_creation_rate
0            Facebook               64.12
1          Google Ads               63.38
2           Instagram               62.64
3            Referral               62.41
4             Organic               61.72

#### 16. Rank Customers by Total Spend

In [20]:
query = """
select
    customer_id,
    round(sum(cost_of_the_order), 2) as total_spend,
    rank() over (
        order by sum(cost_of_the_order) desc
    ) as spending_rank
from product_events
group by customer_id
"""

pd.read_sql(query, engine)

      customer_id  total_spend  spending_rank
0           52832       225.80              1
1          250494       183.83              2
2           47440       158.18              3
3          276192       146.46              4
4           83287       139.31              5
...           ...          ...            ...
1195        64754         5.34           1196
1196       339144         5.05           1197
1197       318665         4.90           1198
1198        50123         4.85           1199
1199       133617         4.75           1200

[1200 rows x 3 columns]

#### 17. Dense Rank Customers by Total Spend

In [21]:
query = """
select
    customer_id,
    round(sum(cost_of_the_order), 2) as total_spend,
    dense_rank() over (
        order by sum(cost_of_the_order) desc
    ) as spending_rank
from product_events
group by customer_id
"""

pd.read_sql(query, engine)

      customer_id  total_spend  spending_rank
0           52832       225.80              1
1          250494       183.83              2
2           47440       158.18              3
3          276192       146.46              4
4           83287       139.31              5
...           ...          ...            ...
1195        64754         5.34            581
1196       339144         5.05            582
1197       318665         4.90            583
1198        50123         4.85            584
1199       133617         4.75            585

[1200 rows x 3 columns]

#### 18. Row Number by Customer Spend

In [22]:
query = """
select
    customer_id,
    round(sum(cost_of_the_order), 2) as total_spend,
    row_number() over (
        order by sum(cost_of_the_order) desc
    ) as row_num
from product_events
group by customer_id
"""

pd.read_sql(query, engine)

      customer_id  total_spend  row_num
0           52832       225.80        1
1          250494       183.83        2
2           47440       158.18        3
3          276192       146.46        4
4           83287       139.31        5
...           ...          ...      ...
1195        64754         5.34     1196
1196       339144         5.05     1197
1197       318665         4.90     1198
1198        50123         4.85     1199
1199       133617         4.75     1200

[1200 rows x 3 columns]